INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (1,'Measurabl HQ','707 Broadway Suite 1000','San Diego','CA',92101);
INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (2,'Arclight','4425 La Jolla Village Dr','San Diego','CA',92122);
INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (3,'TGI Fridays','743 Fifth Ave','San Diego','CA',92101);
INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (4,'Tavern+Bowl East Village','930 Market St','San Diego','CA',92101);
INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (5,'Bellagio','3600 S Las Vegas Blvd','Las Vegas','NV',89109);
INSERT INTO sites(id,name,address,city,state,zipcode) VALUES (6,'Petco Park','100 Park Blvd','San Diego','CA',92101);

INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('MSR Office - Suite 1',1,1,3000,54);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('MSR Office - Suite 2',2,1,3000,54);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('MSR Office - Suite 3',3,1,3000,54);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('MSR Data Center',4,1,4000,4);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Theaters',5,2,50000,40);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Watering Hole',6,2,15000,16);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('TGI Fridays',7,3,35000,16);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Bowling',8,4,20000,36);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Tavern',9,4,10000,16);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Gaming',10,5,1000000,37);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Unce Unce',11,5,50000,35);
INSERT INTO site_uses(description,id,site_id,size_sqft,use_type_id) VALUES ('Ball Park',12,6,560000,47);

INSERT INTO use_types(id,name) VALUES (1,'Banking/Financial Services');
INSERT INTO use_types(id,name) VALUES (2,'Bank Branch');
INSERT INTO use_types(id,name) VALUES (3,'Other - Banking/Financial Services');
INSERT INTO use_types(id,name) VALUES (4,'Data Center');
INSERT INTO use_types(id,name) VALUES (5,'Education');
INSERT INTO use_types(id,name) VALUES (6,'Adult Education');
INSERT INTO use_types(id,name) VALUES (7,'College/University');
INSERT INTO use_types(id,name) VALUES (8,'K-12 School');
INSERT INTO use_types(id,name) VALUES (9,'Pre-school/Daycare');
INSERT INTO use_types(id,name) VALUES (10,'Vocational School');
INSERT INTO use_types(id,name) VALUES (11,'Other - Education');
INSERT INTO use_types(id,name) VALUES (12,'Food Sales & Service');
INSERT INTO use_types(id,name) VALUES (13,'Cafeteria');
INSERT INTO use_types(id,name) VALUES (14,'Food Sales');
INSERT INTO use_types(id,name) VALUES (15,'Food Service');
INSERT INTO use_types(id,name) VALUES (16,'Restaurant/Bar');
INSERT INTO use_types(id,name) VALUES (17,'Fast Food Restaurant');
INSERT INTO use_types(id,name) VALUES (18,'Restaurant');
INSERT INTO use_types(id,name) VALUES (19,'Other - Restaurant/Bar');
INSERT INTO use_types(id,name) VALUES (20,'Supermarket/Grocery Store');
INSERT INTO use_types(id,name) VALUES (21,'Wholesale Club/Supercenter');
INSERT INTO use_types(id,name) VALUES (22,'Other - Food Sales & Service');
INSERT INTO use_types(id,name) VALUES (23,'Healthcare');
INSERT INTO use_types(id,name) VALUES (24,'Ambulatory Surgical Center');
INSERT INTO use_types(id,name) VALUES (25,'Hospital');
INSERT INTO use_types(id,name) VALUES (26,'General Medical & Surgical Hospital');
INSERT INTO use_types(id,name) VALUES (27,'Other - Specialty Hospital');
INSERT INTO use_types(id,name) VALUES (28,'Outpatient Rehabilitation/Physical Therapy');
INSERT INTO use_types(id,name) VALUES (29,'Urgent Care/Clinic/Other Outpatient');
INSERT INTO use_types(id,name) VALUES (30,'Other - Healthcare');
INSERT INTO use_types(id,name) VALUES (31,'Hotel');
INSERT INTO use_types(id,name) VALUES (32,'Laboratory');
INSERT INTO use_types(id,name) VALUES (33,'Leisure');
INSERT INTO use_types(id,name) VALUES (34,'Aquarium');
INSERT INTO use_types(id,name) VALUES (35,'Bar/Nightclub');
INSERT INTO use_types(id,name) VALUES (36,'Bowling Alley');
INSERT INTO use_types(id,name) VALUES (37,'Casino');
INSERT INTO use_types(id,name) VALUES (38,'Fitness Center/Health Club/Gym');
INSERT INTO use_types(id,name) VALUES (39,'Ice/Curling Rink');
INSERT INTO use_types(id,name) VALUES (40,'Movie Theater');
INSERT INTO use_types(id,name) VALUES (41,'Museum');
INSERT INTO use_types(id,name) VALUES (42,'Performing Arts');
INSERT INTO use_types(id,name) VALUES (43,'Roller Rink');
INSERT INTO use_types(id,name) VALUES (44,'Stadium');
INSERT INTO use_types(id,name) VALUES (45,'Closed Stadium');
INSERT INTO use_types(id,name) VALUES (46,'Indoor Arena');
INSERT INTO use_types(id,name) VALUES (47,'Open Stadium');
INSERT INTO use_types(id,name) VALUES (48,'Race Track');
INSERT INTO use_types(id,name) VALUES (49,'Other - Stadium');
INSERT INTO use_types(id,name) VALUES (50,'Swimming Pool');
INSERT INTO use_types(id,name) VALUES (51,'Zoo');
INSERT INTO use_types(id,name) VALUES (52,'Other - Leisure');
INSERT INTO use_types(id,name) VALUES (53,'Manufacturing/Industrial Plant');
INSERT INTO use_types(id,name) VALUES (54,'Office');
INSERT INTO use_types(id,name) VALUES (55,'Financial Office');
INSERT INTO use_types(id,name) VALUES (56,'Medical Office');
INSERT INTO use_types(id,name) VALUES (57,'Office');
INSERT INTO use_types(id,name) VALUES (58,'Veterinary Office');
INSERT INTO use_types(id,name) VALUES (59,'Other - Office');
INSERT INTO use_types(id,name) VALUES (60,'Indoor Parking');
INSERT INTO use_types(id,name) VALUES (61,'Public Assembly');
INSERT INTO use_types(id,name) VALUES (62,'Convention Center');
INSERT INTO use_types(id,name) VALUES (63,'Social/Meeting Hall');
INSERT INTO use_types(id,name) VALUES (64,'Other - Public Assembly');
INSERT INTO use_types(id,name) VALUES (65,'Public Services');
INSERT INTO use_types(id,name) VALUES (66,'Airport');
INSERT INTO use_types(id,name) VALUES (67,'Courthouse');
INSERT INTO use_types(id,name) VALUES (68,'Fire Station');
INSERT INTO use_types(id,name) VALUES (69,'Library');
INSERT INTO use_types(id,name) VALUES (70,'Mailing Center/Post Office');
INSERT INTO use_types(id,name) VALUES (71,'Police Station');
INSERT INTO use_types(id,name) VALUES (72,'Transportation Terminal/Station');
INSERT INTO use_types(id,name) VALUES (73,'Other - Public Services');
INSERT INTO use_types(id,name) VALUES (74,'Religious Worship Facility');
INSERT INTO use_types(id,name) VALUES (75,'Residential');
INSERT INTO use_types(id,name) VALUES (76,'Barracks');
INSERT INTO use_types(id,name) VALUES (77,'Multifamily Housing');
INSERT INTO use_types(id,name) VALUES (78,'1-4 stories - Multifamily Low-rise');
INSERT INTO use_types(id,name) VALUES (79,'5-10 stories - Multifamily Mid-rise');
INSERT INTO use_types(id,name) VALUES (80,'10+ stories - Multifamily High-rise');
INSERT INTO use_types(id,name) VALUES (81,'Other - Multifamily');
INSERT INTO use_types(id,name) VALUES (82,'Prison/Incarceration');
INSERT INTO use_types(id,name) VALUES (83,'Residential Care Facility');
INSERT INTO use_types(id,name) VALUES (84,'Residence Hall/Dormitory');
INSERT INTO use_types(id,name) VALUES (85,'Senior Care Community');
INSERT INTO use_types(id,name) VALUES (86,'Single Family Home');
INSERT INTO use_types(id,name) VALUES (87,'Other - Residential');
INSERT INTO use_types(id,name) VALUES (88,'Retail');
INSERT INTO use_types(id,name) VALUES (89,'Automobile Dealership');
INSERT INTO use_types(id,name) VALUES (90,'Convenience Store');
INSERT INTO use_types(id,name) VALUES (91,'Convenience Store with Gas Station');
INSERT INTO use_types(id,name) VALUES (92,'Convenience Store without Gas Station');
INSERT INTO use_types(id,name) VALUES (93,'Mall');
INSERT INTO use_types(id,name) VALUES (94,'Enclosed Mall');
INSERT INTO use_types(id,name) VALUES (95,'Lifestyle Center');
INSERT INTO use_types(id,name) VALUES (96,'Strip Mall');
INSERT INTO use_types(id,name) VALUES (97,'Other - Mall');
INSERT INTO use_types(id,name) VALUES (98,'Retail Store');
INSERT INTO use_types(id,name) VALUES (99,'Other - Retail');
INSERT INTO use_types(id,name) VALUES (100,'Utility');
INSERT INTO use_types(id,name) VALUES (101,'Drinking Water Treatment & Distribution');
INSERT INTO use_types(id,name) VALUES (102,'Energy/Power Station');
INSERT INTO use_types(id,name) VALUES (103,'Wastewater Treatment Plant');
INSERT INTO use_types(id,name) VALUES (104,'Other - Utility');
INSERT INTO use_types(id,name) VALUES (105,'Warehouse/Storage');
INSERT INTO use_types(id,name) VALUES (106,'Self-Storage Facility');
INSERT INTO use_types(id,name) VALUES (107,'Warehouse/Distribution Center');
INSERT INTO use_types(id,name) VALUES (108,'Distribution Center');
INSERT INTO use_types(id,name) VALUES (109,'Non-Refrigerated Warehouse');
INSERT INTO use_types(id,name) VALUES (110,'Refrigerated Warehouse');
INSERT INTO use_types(id,name) VALUES (111,'Other - Warehouse/Storage');
INSERT INTO use_types(id,name) VALUES (112,'Other');
